name: Codecov

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
    - name: Install npm
      run: npm install -g npm@8
    - name: Install Dependencies
      run: npm ci

    - name: Run Unit Tests
      run: xvfb-run --auto-servernum npm run coverage
      env:
        NODE_ENV: production

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
